### ISSUE TITLE
Wear is put token

### ISSUE THREAD

**Issue by Khanmanan** [MichaelPavlovic/DiscordBot-V12#2]
Waer is put token ?

**Comment by BRAVO68WEB** [comment]
You Have to the Discord Bot Token in Project Environment Variable..

**Comment by lepoulpi17** [comment]
Where is root forlder ?

**Comment by Anonymous9172** [comment]
You usually put tokens in a config file. So look for a config.json file

**Comment by chrispiciullo** [comment]
> Where is root forlder ?

The same folder that package.json is in.



> You usually put tokens in a config file. So look for a config.json file

Not in this case. the dev is using [dotenv](https://www.npmjs.com/package/dotenv) which is far more secure than a config.json (or similar) file.

**Comment by XzFrosT** [comment]
> > Where is root forlder ?
> 
> The same folder that package.json is in.
> 
> > You usually put tokens in a config file. So look for a config.json file
> 
> Not in this case. the dev is using [dotenv](https://www.npmjs.com/package/dotenv) which is far more secure than a config.json (or similar) file.

What is bot prefix?

**Comment by chrispiciullo** [comment]
> What is bot prefix?

Seriously..? The questions you guys are asking lead me to believe you're all either trolling, or need to learn JS and read about Discord bot in general...

The prefix is the character that triggers your commands, such as "!" or "+"

**Comment by EvanDowding** [comment]
> > What is bot prefix?
> 
> Seriously..? The questions you guys are asking lead me to believe you're all either trolling, or need to learn JS and/or read about Discord bots in general...
> 
> The prefix is the character that triggers your commands, such as "!" or "+"

@chrispiciullo stop helping them.

**Comment by Ryan-Ray-Offical** [comment]
> > What is bot prefix?
> 
> Seriously..? The questions you guys are asking lead me to believe you're all either trolling, or need to learn JS and/or read about Discord bots in general...
> 
> The prefix is the character that triggers your commands, such as "!" or "+"

They are prob trolling, just ignore these kids.

If you want to learn how to code just go to https://discordjs.guide/
tbh im just using this to see if there are any interesting command ideas that i don't already have

**Comment by XzFrosT** [comment]
> > > What is bot prefix?
> > 
> > 
> > Seriously..? The questions you guys are asking lead me to believe you're all either trolling, or need to learn JS and/or read about Discord bots in general...
> > The prefix is the character that triggers your commands, such as "!" or "+"
> 
> They are prob trolling, just ignore these kids.
> 
> If you want to learn how to code just go to https://discordjs.guide/
> tbh im just using this to see if there are any interesting command ideas that i don't already have

I understand js, just don't understand discord api lol

**Comment by Ryan-Ray-Offical** [comment]
> > > > What is bot prefix?
> > > 
> > > 
> > > Seriously..? The questions you guys are asking lead me to believe you're all either trolling, or need to learn JS and/or read about Discord bots in general...
> > > The prefix is the character that triggers your commands, such as "!" or "+"
> > 
> > 
> > They are prob trolling, just ignore these kids.
> > If you want to learn how to code just go to https://discordjs.guide/
> > tbh im just using this to see if there are any interesting command ideas that i don't already have
> 
> I understand js, just don't understand discord api lol

https://discordjs.guide/

**Comment by sachinl0har** [comment]
.env file
